import React, { useMemo } from 'react';
import { ArrowRight, CheckCircle2, Loader2, Palette, FileText } from 'lucide-react';
import { STEPS } from '../../constants/prompts';
import StreamOutputCard from '../Common/StreamOutputCard';
import DesignReviewBar from './DesignReviewBar';

/**
 * Design Plan stage matching screen2.png reference:
 * - Top prompt bar with PLAN-ID, status, confidence
 * - Summary meta cards (target, layout, color mode, tech stack)
 * - Full-width streaming design plan output in rich markdown
 * - Action bar at bottom
 */
export default function DesignStageView({
  step,
  designPlan,
  streaming,
  statusMessage,
  streamEndRef,
  onProceed,
  onRefine,
  prompt,
  sessionId,
}) {
  const isReview = step === STEPS.DESIGN_REVIEW;
  const isComplete = Boolean(!streaming && isReview);

  const tokenEstimate = useMemo(() => {
    if (!designPlan) return 0;
    return Math.round(designPlan.length / 4);
  }, [designPlan]);

  // Dynamically parse real milestones emitted by the model in real-time
  const dynamicMilestones = useMemo(() => {
    if (!designPlan || designPlan.trim().length === 0) {
      return [
        { label: 'Formulating Visual Identity', status: streaming ? 'active' : 'queued' },
        { label: 'Tailored Color System', status: 'queued' },
        { label: 'Typography & Hierarchy', status: 'queued' },
        { label: 'Section-by-Section Layout', status: 'queued' },
        { label: 'UI Component Specifications', status: 'queued' },
      ];
    }

    // Extract all ## headings generated by the model
    const rawHeadings = [...designPlan.matchAll(/^##\s+([^\n\r]+)/gm)].map((m) => m[1].trim());

    if (rawHeadings.length === 0) {
      return [
        { label: 'Synthesizing Architecture...', status: streaming ? 'active' : 'done' }
      ];
    }

    return rawHeadings.map((heading, idx) => {
      // Clean leading numbers or decorative symbols for crisp display
      const cleanLabel = heading
        .replace(/^[0-9]+[\.\)]\s*/, '')
        .replace(/^[\p{Emoji}\p{Symbol}\p{Punctuation}\s]+/u, '')
        .trim() || heading;

      const isLast = idx === rawHeadings.length - 1;
      let status = 'done';
      if (isLast && streaming) {
        status = 'active';
      }

      return {
        label: cleanLabel,
        status,
        index: idx + 1,
      };
    });
  }, [designPlan, streaming]);

  return (
    <div className="flex-1 flex flex-col gap-4 w-full animate-fade-in-up min-h-0 overflow-hidden">
      {/* Prompt Bar */}
      <div className="bg-white border border-slate-200 rounded-xl px-5 py-3 flex items-center justify-between shadow-sm shrink-0">
        <div className="flex items-center gap-3">
          <span className="text-[11px] font-mono font-bold text-indigo-600 bg-indigo-50 border border-indigo-200 px-2 py-0.5 rounded uppercase tracking-wider">
            Prompt
          </span>
          <span className="text-sm text-slate-700 font-medium truncate max-w-md">{prompt}</span>
        </div>
        <div className="flex items-center gap-4 text-[11px] font-mono text-slate-400 tracking-wider">
          <span>PLAN-ID #{sessionId?.slice(-4)?.toUpperCase() || '0000'}-B</span>
          <span className="h-4 w-px bg-slate-200"></span>
          <span>
            STATUS:{' '}
            <span className={`font-semibold ${isComplete ? 'text-emerald-500' : 'text-amber-500'}`}>
              {isComplete ? '● Ready for Synthesis' : '● Generating...'}
            </span>
          </span>
          {isComplete && (
            <>
              <span className="h-4 w-px bg-slate-200"></span>
              <span>
                CONFIDENCE: <span className="font-semibold text-slate-700">98.4%</span>
              </span>
            </>
          )}
        </div>
      </div>

      {/* Execution Pipeline Status Bar */}
      {streaming && (
        <div className="bg-white border border-slate-200 rounded-xl px-5 py-3 flex items-center gap-3 shadow-sm shrink-0">
          <Palette className="h-4 w-4 text-indigo-500 animate-spin" />
          <span className="font-medium font-mono text-[11px] text-slate-600 tracking-wide">
            {statusMessage || 'Synthesizing design architecture & color tokens...'}
          </span>
        </div>
      )}

      {/* Main Content: Design Plan */}
      <div className="flex-1 flex gap-4 min-h-0 overflow-hidden">
        {/* Left: Design Plan Content */}
        <div className="flex-1 flex flex-col min-h-0 min-w-0">
          <StreamOutputCard
            title="UI Design Plan & System Spec"
            content={designPlan}
            streaming={streaming}
            placeholder="Formulating design plan tokens..."
            scrollRef={streamEndRef}
          />
        </div>

        {/* Right: Dynamic Execution Pipeline Panel */}
        <div className="w-72 shrink-0 bg-white border border-slate-200 rounded-2xl shadow-sm flex flex-col overflow-hidden">
          <div className="px-5 py-3.5 border-b border-slate-100 flex items-center justify-between">
            <span className="text-xs font-bold text-slate-700 uppercase tracking-wider">Live Pipeline</span>
            <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${
              isComplete
                ? 'bg-emerald-50 text-emerald-600 border border-emerald-200'
                : 'bg-indigo-50 text-indigo-600 border border-indigo-200'
            }`}>
              {isComplete ? 'All Complete' : 'Streaming'}
            </span>
          </div>

          <div className="flex-1 p-5 overflow-y-auto custom-scrollbar">
            <div className="flex items-center justify-between mb-4">
              <p className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">Model Milestones</p>
              <span className="text-[10px] font-mono text-indigo-600 font-semibold">
                {dynamicMilestones.filter(m => m.status === 'done').length}/{dynamicMilestones.length}
              </span>
            </div>

            <div className="space-y-3.5">
              {dynamicMilestones.map((item, idx) => (
                <div key={idx} className="flex items-start gap-2.5">
                  {item.status === 'done' ? (
                    <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                  ) : item.status === 'active' ? (
                    <div className="h-4 w-4 rounded-full bg-indigo-100 border-2 border-indigo-400 flex items-center justify-center shrink-0 mt-0.5">
                      <Loader2 className="h-2.5 w-2.5 text-indigo-500 animate-spin" />
                    </div>
                  ) : (
                    <div className="h-4 w-4 rounded-full border-2 border-slate-200 flex items-center justify-center shrink-0 mt-0.5">
                      <span className="text-[8px] font-bold text-slate-400">{idx + 1}</span>
                    </div>
                  )}
                  <div className="flex-1 min-w-0">
                    <p className={`text-xs font-semibold truncate ${
                      item.status === 'done' ? 'text-slate-800' : item.status === 'active' ? 'text-indigo-700' : 'text-slate-400'
                    }`}>
                      {item.label}
                    </p>
                    <p className={`text-[10px] font-mono mt-0.5 ${
                      item.status === 'done' ? 'text-emerald-500' : item.status === 'active' ? 'text-indigo-400' : 'text-slate-300'
                    }`}>
                      {item.status === 'done' ? 'Synthesized' : item.status === 'active' ? 'Synthesizing...' : 'Queued'}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Bottom Stats */}
          <div className="border-t border-slate-100 px-5 py-3 grid grid-cols-2 gap-3">
            <div>
              <div className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">Tokens</div>
              <div className="text-xs font-semibold text-indigo-600 mt-0.5 font-mono">{tokenEstimate.toLocaleString()}</div>
            </div>
            <div>
              <div className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">Stage</div>
              <div className="text-xs font-semibold text-slate-700 mt-0.5">Design Plan</div>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Action Bar */}
      {isComplete && (
        <div className="bg-white border border-slate-200 rounded-xl px-5 py-3 flex items-center justify-between shadow-sm shrink-0">
          <div className="flex items-center gap-2 text-xs text-slate-500">
            <span className="h-2 w-2 rounded-full bg-emerald-400"></span>
            <span className="font-mono tracking-wide">Architecture plan finalized and locked</span>
            <span className="text-slate-300 mx-1">•</span>
            <span>Press <span className="font-mono bg-slate-100 border border-slate-200 px-1 py-0.5 rounded text-[10px]">P</span> to inspect schema</span>
          </div>
          <div className="flex items-center gap-3">
            <DesignReviewBar onRefine={onRefine} streaming={streaming} />
            <button
              onClick={onProceed}
              className="inline-flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-sm px-5 py-2.5 rounded-xl shadow-md shadow-indigo-600/20 transition cursor-pointer"
            >
              <span>Proceed to Live Synthesis</span>
              <ArrowRight className="h-4 w-4" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
